import React from 'react';
import { Link } from 'react-router-dom';
import { fastTrackData as data } from '../data/fastTrackPhd.js';
import { MegaIcon } from '../MegaServicePanel.jsx';
import { Section, FAQAccordion } from '../components/services/AdmissionSections.jsx';
import './phdAdmission.css';
import './fastTrackPhd.css';

function PathwayCards({ items }) {
  return <div className="ad-grid ad-grid--three">{items.map(item => <article className="ad-card ft-card" key={item.title}><MegaIcon type={item.icon}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div>;
}

function Roadmap({ items }) {
  return <ol className="ft-roadmap">{items.map((item, index) => <li key={item.period}><span className="ft-milestone" aria-hidden="true">{String(index + 1).padStart(2, '0')}</span><div className="ft-period">{item.period}</div><div><h3>{item.title}</h3><p>{item.text}</p></div></li>)}</ol>;
}

function Investment({ fees, onEnquire }) {
  return <><table className="ad-comparison ft-fees"><caption className="ad-sr-only">Fast-track pathway fee categories</caption><thead><tr><th scope="col">Fee Category</th><th scope="col">Scope & Payment Information</th><th scope="col">Investment</th></tr></thead><tbody>{fees.map(fee => <tr key={fee.title}><th scope="row">{fee.title}</th><td><p>{fee.scope}</p><p className="ad-note">{fee.note}</p></td><td><strong>{fee.price}</strong></td></tr>)}</tbody></table><div className="ad-package-mobile">{fees.map(fee => <article className="ad-card" key={fee.title}><h3>{fee.title}</h3><strong className="ft-price">{fee.price}</strong><p>{fee.scope}</p><p className="ad-note">{fee.note}</p></article>)}</div><div className="ad-actions"><button className="btn primary" onClick={onEnquire}>Request an Itemised Quote <span aria-hidden="true">↗</span></button></div></>;
}

export default function FastTrackPhd({ onEnquire, onOpenStart }) {
  return <div className="admission-page fast-track-page">
    <nav className="container ad-breadcrumb" aria-label="Breadcrumb"><ol><li><Link to="/">Home</Link></li><li><button onClick={onOpenStart}>Research Services</button></li><li aria-current="page">{data.title}</li></ol></nav>
    <section className="ad-hero"><div className="container ad-hero-grid"><div><span className="section-kicker">YOUR EXPERIENCE. YOUR RESEARCH. YOUR NEXT CHAPTER.</span><h1>{data.title}</h1><p className="ft-subheading">A focused, publication-based doctoral preparation pathway for experienced professionals ready to bring their research together.</p><p>Build on the work you have already done. Our structured mentoring helps you assess your portfolio, develop a coherent research narrative and prepare for the academic requirements of an appropriate institution.</p><div className="ad-actions"><button className="btn primary" onClick={onEnquire}>Enquire Now <span aria-hidden="true">↗</span></button><a className="btn ghost" href="#roadmap">Explore the Roadmap</a></div><p className="ad-note">Approx. six months refers to the proposed support schedule, not a guaranteed doctoral award. Eligibility and completion depend on the awarding institution and your research readiness.</p></div><aside className="ad-hero-visual" aria-label="Pathway overview"><div className="ad-visual-orbit" aria-hidden="true"><MegaIcon type="book"/></div><span className="ad-visual-label">TURN A PORTFOLIO INTO A CONNECTED CONTRIBUTION</span><h2>Research that tells<br/>a bigger story.</h2><ul>{data.highlights.map(point => <li key={point}><span aria-hidden="true">✓</span>{point}</li>)}</ul><div className="ad-visual-footer"><span>PUBLICATIONS → SYNTHESIS → DEFENCE</span></div></aside></div></section>
    <Section eyebrow="UNDERSTANDING THE PATHWAY" title="What is a PhD by Research Publication?"><div className="ft-explainer"><div><p>A publication-based doctorate places a connected body of original research at the centre of the assessment. Research articles provide evidence of the contribution, while a synthesis or research report explains how the work fits together and advances knowledge.</p><p>This can be a relevant option for experienced professionals and researchers with substantial work to present. Routes based on prior publications differ from doctoral programmes in which articles are produced during registration; the institution’s regulations determine which model applies.</p><p className="ad-note">Read an institutional example: {data.sources.map(source => <a className="text-link" key={source.href} href={source.href} target="_blank" rel="noreferrer">{source.label} ↗</a>)}. This is background information, not a partner programme listing.</p></div><div className="ad-card ft-principle"><MegaIcon type="badge"/><h3>One coherent research contribution</h3><p>Your articles should support a shared line of enquiry. The report makes their connection, originality and your individual contribution clear.</p><p className="ad-note">You remain the researcher and author. Support covers mentoring and review.</p></div></div></Section>
    <Section className="ad-soft" title="Why Choose This Path?" intro="A research-led approach to organising existing expertise, with practical support for the next stage of your academic journey."><PathwayCards items={data.features}/></Section>
    <Section id="roadmap" eyebrow="A CLEAR PLAN FOR EACH STAGE" title="Six-Month Roadmap" intro="An indicative preparation schedule for applicants with suitable research foundations. Milestones are adapted after an eligibility review; publication decisions and university processes remain outside our control."><Roadmap items={data.roadmap}/></Section>
    <Section className="ad-soft" title="Program Requirements" intro="Use these areas as a preparation checklist. Confirm the final requirements directly with your chosen institution before committing to a pathway."><PathwayCards items={data.requirements}/></Section>
    <Section title="Investment / Fees" intro="Keep institutional charges separate from research support. We discuss your portfolio and support needs before providing an itemised quotation."><Investment fees={data.fees} onEnquire={onEnquire}/></Section>
    <Section className="ad-soft" title="Frequently Asked Questions" intro="Understand the academic requirements and practical commitments before taking the next step."><FAQAccordion items={data.faqs}/></Section>
    <section className="ad-cta"><div className="container ad-cta-inner"><div><h2>Explore the Fast-Track Research Publication Pathway</h2><p>Discuss your experience, publications and academic goals. Start with a clear view of your eligibility, portfolio readiness and the support you may need.</p></div><div className="ad-actions"><button className="btn primary" onClick={onEnquire}>Enquire Now <span aria-hidden="true">↗</span></button><button className="btn ghost" onClick={onEnquire}>Schedule Consultation</button></div></div></section>
  </div>;
}
