import React from 'react';
import { Link } from 'react-router-dom';
import { embarkingData as data } from '../data/phdEmbarking.js';
import { MegaIcon } from '../MegaServicePanel.jsx';
import { Section, Testimonials } from '../components/services/AdmissionSections.jsx';
import './phdAdmission.css';
import './phdEmbarking.css';

function ResearchFactors() {
  return <div className="ad-grid ad-grid--three">{data.factors.map((factor, index) => <article className="ad-card journey-factor" key={factor.title}><div className="ad-card-top"><MegaIcon type={factor.icon}/><span>{String(index + 1).padStart(2, '0')}</span></div><h3>{factor.title}</h3><p>{factor.intro}</p><dl>{factor.points.map(([title, text]) => <div key={title}><dt>{title}</dt><dd>{text}</dd></div>)}</dl></article>)}</div>;
}

function RelatedServices() {
  return <div className="ad-grid ad-grid--three journey-related">{data.relatedServices.map(service => <Link className="ad-card" key={service.title} to={service.href || '#'} aria-disabled={!service.href} onClick={event => { if (!service.href) event.preventDefault(); }}><MegaIcon type={service.icon}/><span><strong>{service.title}</strong>{!service.href && <small>Service page coming soon</small>}</span>{service.href && <span aria-hidden="true">↗</span>}</Link>)}</div>;
}

export default function PhdEmbarking({ onQuote, onOpenStart, callbackForm }) {
  return <div className="admission-page journey-page">
    <nav className="container ad-breadcrumb" aria-label="Breadcrumb"><ol><li><Link to="/">Home</Link></li><li><button onClick={onOpenStart}>Research Services</button></li><li aria-current="page">{data.title}</li></ol></nav>
    <section className="ad-hero"><div className="container ad-hero-grid"><div><span className="section-kicker">START WITH PURPOSE. PLAN WITH CONFIDENCE.</span><h1>{data.title}</h1><p className="journey-lead">A doctorate begins with a question. A sustainable research journey begins with a plan.</p><p>A PhD is a long-term commitment to exploring evidence, developing original ideas and communicating them through research writing. The process involves testing your thinking, responding to feedback and gradually building an independent contribution.</p><p>Time, resources and access to guidance can shape every stage. Determination matters, but so does thoughtful preparation: a meaningful purpose, an appropriate research environment and a plan you can realistically follow.</p><div className="ad-actions"><a className="btn primary" href="#contact">Talk to a Research Mentor <span aria-hidden="true">↗</span></a><a className="btn ghost" href="#research-factors">Explore the Key Factors</a></div></div><aside className="ad-hero-visual" aria-label="Research journey planning"><div className="ad-visual-orbit" aria-hidden="true"><MegaIcon type="compass"/></div><span className="ad-visual-label">A STRONG FOUNDATION FOR YOUR NEXT CHAPTER</span><h2>Your purpose.<br/>Your ideas.<br/>Your journey.</h2><ul>{data.highlights.map(point => <li key={point}><span aria-hidden="true">✓</span>{point}</li>)}</ul><div className="ad-visual-footer"><span>REFLECT → PLAN → RESEARCH</span></div></aside></div></section>
    <Section eyebrow="BE CLEAR ABOUT YOUR REASON" title="Why PhD?" intro="Before comparing universities or choosing a topic, pause to ask what doctoral research means to you. Your purpose should be specific enough to guide decisions and strong enough to sustain you through uncertainty."><div className="ad-grid ad-grid--three">{data.motivations.map(item => <article className="ad-card" key={item.title}><MegaIcon type={item.icon}/><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><div className="journey-reflection"><strong>A useful starting question</strong><p>What do I want to understand or change through this research, and why is a PhD the right way to pursue it?</p></div></Section>
    <Section id="research-factors" className="ad-soft" title="Some Factors to Consider" intro="A good start brings your ambitions into conversation with the realities of your institution, supervision and research plan."><ResearchFactors/></Section>
    <section className="ad-cta ad-cta--light"><div className="container ad-cta-inner"><div><h2>Need guidance before starting your PhD journey?</h2><p>Talk through your interests, practical constraints and the decisions you need to make next.</p></div><a className="btn primary" href="#contact">Talk to a Research Mentor <span aria-hidden="true">↗</span></a></div></section>
    <Section title="Other Services" intro="Explore the kinds of support available across the research lifecycle. Dedicated pages for these services are coming soon; you can discuss them through the callback form below."><RelatedServices/></Section>
    <section className="ad-cta"><div className="container ad-cta-inner"><div><h2>Need urgent research assistance?</h2><p>Share your current stage, the difficulty you are facing and your deadline so we can discuss a suitable scope of support.</p></div><button className="btn primary" onClick={onQuote}>Request a Quote <span aria-hidden="true">↗</span></button></div></section>
    <Section title="What Research Scholars Say"><Testimonials items={data.reviews}/></Section>
    <Section id="contact" className="ad-soft" eyebrow="LET’S DISCUSS YOUR NEXT STEP" title="Request a Callback" intro="Tell us about your research interests and where you would welcome guidance. Use the requirement field to include your current stage and a convenient time to speak."><div className="ad-consult-grid"><aside><span className="section-kicker">PERSONAL GUIDANCE, A PRACTICAL START</span><h3>You do not need every answer before beginning the conversation.</h3><p>Bring your questions about choosing a topic, finding a supervisor or deciding whether your study is feasible. We can help you organise the next steps.</p><p className="ad-note">Required fields are marked with an asterisk. Your enquiry is sent through the site’s existing contact service.</p></aside><div className="ad-card">{callbackForm}</div></div></Section>
  </div>;
}
