INSERT INTO services (name, slug, category, description, sort_order) VALUES
('Topic and Research Proposal', 'topic-and-research-proposal', 'research', 'Research topic selection, gap identification and proposal planning.', 10),
('Problem Statement', 'problem-statement', 'research', 'Research problem identification and statement development.', 20),
('Base Papers', 'base-papers', 'research', 'Base paper selection and literature foundation support.', 30),
('Chapters Writing', 'chapters-writing', 'thesis', 'Thesis chapter planning, writing and structural guidance.', 40),
('Questionnaire and Experiments', 'questionnaire-and-experiments', 'research', 'Questionnaire design, pilot planning and experiment structure.', 50),
('Implementation', 'implementation', 'technical', 'Research model, algorithm and software implementation support.', 60),
('Analysis', 'analysis', 'analysis', 'Data preparation, statistical analysis and result interpretation.', 70),
('Editing', 'editing', 'thesis', 'Academic editing, clarity, coherence and manuscript review.', 80),
('Formatting', 'formatting', 'thesis', 'University and journal formatting for academic documents.', 90),
('Journal Papers', 'journal-papers', 'publication', 'Journal manuscript structure, refinement and submission preparation.', 100),
('IEEE Papers', 'ieee-papers', 'publication', 'IEEE manuscript writing, referencing and formatting support.', 110),
('Thought Clearing', 'thought-clearing', 'consultation', 'Research direction, objective and methodology clarification.', 120),
('Development Editing', 'development-editing', 'thesis', 'Structural manuscript development and argument improvement.', 130),
('Research Design', 'research-design', 'research', 'Research approach, variables, sampling and analysis planning.', 140),
('Review Article', 'review-article', 'publication', 'Literature screening, synthesis and review article development.', 150),
('Empirical Article', 'empirical-article', 'publication', 'Observed-data article preparation and evidence-based discussion.', 160),
('Technical Article', 'technical-article', 'publication', 'Technical methodology, evaluation and research article support.', 170),
('Qualitative Data Analysis', 'qualitative-data-analysis', 'analysis', 'Coding, thematic analysis and qualitative interpretation.', 180),
('Quantitative Data Analysis', 'quantitative-data-analysis', 'analysis', 'Statistics, regression, ANOVA and hypothesis testing support.', 190),
('Matlab Projects', 'matlab-projects', 'technical', 'MATLAB programming, simulation and research implementation.', 200),
('Simulink Projects', 'simulink-projects', 'technical', 'Simulink modelling, control systems and validation support.', 210),
('Python Projects', 'python-projects', 'technical', 'Python data science, ML, automation and scientific computing.', 220),
('Java Projects', 'java-projects', 'technical', 'Java application, algorithm and backend project support.', 230),
('Ansys Projects', 'ansys-projects', 'technical', 'Finite element, CFD, meshing and simulation interpretation.', 240)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    category = VALUES(category),
    description = VALUES(description),
    sort_order = VALUES(sort_order),
    is_active = 1;
